package csg;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Jiang He
 * @version 2.0
 */
public enum CourseSitePropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    CSG_OK_PROMPT,
    OH_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    CSG_TAB_PANE,
    CSG_CENTER_PANE,
    CSG_LEFT_PANE,
    CSG_TAS_HEADER_PANE,
    CSG_TAS_HEADER_LABEL,
    CSG_GRAD_UNDERGRAD_TAS_PANE,
    CSG_ALL_RADIO_BUTTON,
    CSG_GRAD_RADIO_BUTTON,
    CSG_UNDERGRAD_RADIO_BUTTON,
    CSG_TAS_HEADER_TEXT_FIELD,
    CSG_TAS_TABLE_VIEW,
    CSG_NAME_TABLE_COLUMN,
    CSG_EMAIL_TABLE_COLUMN,
    CSG_SLOTS_TABLE_COLUMN,
    CSG_TYPE_TABLE_COLUMN,
    CSG_OH_VBOX,

    CSG_ADD_TA_PANE,
    CSG_NAME_TEXT_FIELD,
    CSG_EMAIL_TEXT_FIELD,
    CSG_ADD_TA_BUTTON,

    CSG_RIGHT_PANE,
    CSG_OFFICE_HOURS_HEADER_PANE,
    CSG_OFFICE_HOURS_HEADER_LABEL,
    CSG_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    OH_START_TIME_LABEL,
    OH_END_TIME_LABEL,
    OH_START_TIME_COMBO_BOX,
    OH_END_TIME_COMBO_BOX,
    CSG_FOOLPROOF_SETTINGS,
    CSG_DELETE_TA_BUTTON,
    
    // FOR THE EDIT DIALOG
    CSG_TA_EDIT_DIALOG,
    CSG_TA_DIALOG_GRID_PANE,
    CSG_TA_DIALOG_HEADER_LABEL, 
    CSG_TA_DIALOG_NAME_LABEL,
    CSG_TA_DIALOG_NAME_TEXT_FIELD,
    CSG_TA_DIALOG_EMAIL_LABEL,
    CSG_TA_DIALOG_EMAIL_TEXT_FIELD,
    CSG_TA_DIALOG_TYPE_LABEL,
    CSG_TA_DIALOG_TYPE_BOX,
    CSG_TA_DIALOG_GRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_OK_BOX,
    CSG_TA_DIALOG_OK_BUTTON, 
    CSG_TA_DIALOG_CANCEL_BUTTON, 
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    CSG_NO_TA_SELECTED_TITLE, CSG_NO_TA_SELECTED_CONTENT,
    
    // tabs
    CSG_SITE_TAB_BUTTON,
    CSG_SYLLUBUS_TAB_BUTTON,
    CSG_MEETING_TIME_TAB_BUTTON,
    CSG_SCHEDULE_TAB_BUTTON,
    CSG_OFFICE_HOUR_TAB_BUTTON,
    
    //tab1
    SITE_BANNER_HBOX,
    SITE_PAGE_HBOX,
    SITE_STYLE_HBOX,
    SITE_INSTRUCTOR_HBOX,
    SITE_SCROLL_PANE,
    
    //tab1 banner
    SITE_BANNER_LABEL,
    SITE_SBJ_COMBO_BOX,
    SITE_NUMBER_COMBO_BOX,
    SITE_SBJ_LABEL,
    SITE_NUMBER_LABEL,
    SITE_YEAR_LABEL,
    SITE_SEMESTER_LABEL,
    SITE_SEMESTER_COMBO_BOX,
    SITE_YEAR_COMBO_BOX,
    SITE_TITLE_LABEL,
    SITE_TITLE_TEXT_FIELD,
    SITE_EXPORT_DIR_LABEL,
    SITE_EXPORT_DIR,
    
    //tab1 page
    SITE_PAGE_LABEL,
    SITE_HOME_CHECK_BOX,
    SITE_SYLLUBUS_CHECK_BOX,
    SITE_SCHEDULE_CHECK_BOX,
    SITE_HWS_CHECK_BOX,
    
    //tab1 style
    SITE_STYLE_LABEL,
    SITE_NOTE_LABEL,
    SITE_NOTE_DETAIL_LABEL,
    SITE_FAV_ICON_BUTTON,
    SITE_NAVBAR_BUTTON,
    SITE_LEFT_FOTTER_BUTTON,
    SITE_RIGHT_FOTTER_BUTTON,
    SITE_FONT_COLOR_LABEL,
    SITE_CSS_COMBO_BOX,
    SITE_OFFICE_HOURS_LABEL,
    SITE_OFFICE_HOURS_TEXT_AREA,
    SITE_OFFICE_HOURS_EXPAND_BUTTON,
    SITE_FAV_HBOX, SITE_NAV_HBOX,
    SITE_LF_IMAGE_HBOX, SITE_RF_IMAGE_HBOX,
    
    //tab1 instructor
    SITE_INSTRUCTOR_LABEL,
    SITE_NAME_LABEL,
    SITE_EMAIL_LABEL,
    SITE_NAME_TEXT_FIELD,
    SITE_EMAIL_TEXT_FIELD,
    SITE_ROOM_LABEL,
    SITE_HOME_PAGE_LABEL,
    SITE_ROOM_TEXT_FIELD,
    SITE_HOME_PAGE_TEXT_FIELD,
    
    //tab2
    //labels
    SYLLUBUS_DES_LABEL,
    SYLLUBUS_TOPIC_LABEL,
    SYLLUBUS_PREQ_LABEL,
    SYLLUBUS_OUTCOME_LABEL,
    SYLLUBUS_TEXTBOOK_LABEL,
    SYLLUBUS_GRADED_COMP_LABEL,
    SYLLUBUS_GRADING_NOTE_LABEL,
    SYLLUBUS_ACAD_DIS_LABEL,
    SYLLUBUS_SPEC_ASSIST_LABEL,
    //textfields
    SYLLUBUS_DES_TEXTAREA,
    SYLLUBUS_TOPIC_TEXTAREA,
    SYLLUBUS_PREQ_TEXTAREA,
    SYLLUBUS_OUTCOME_TEXTAREA,
    SYLLUBUS_TEXTBOOK_TEXTAREA,
    SYLLUBUS_GRADED_COMP_TEXTAREA,
    SYLLUBUS_GRADING_NOTE_TEXTAREA,
    SYLLUBUS_ACAD_DIS_TEXTAREA,
    SYLLUBUS_SPEC_ASSIST_TEXTAREA,
    //toggle button
    SYLLUBUS_DES_TOGGLE_BUTTON,
    SYLLUBUS_TOPIC_TOGGLE_BUTTON,
    SYLLUBUS_PREQ_TOGGLE_BUTTON,
    SYLLUBUS_OUTCOME_TOGGLE_BUTTON,
    SYLLUBUS_TEXTBOOK_TOGGLE_BUTTON,
    SYLLUBUS_GRADED_COMP_TOGGLE_BUTTON,
    SYLLUBUS_GRADING_NOTE_TOGGLE_BUTTON,
    SYLLUBUS_ACAD_DIS_TOGGLE_BUTTON,
    SYLLUBUS_SPEC_ASSIST_TOGGLE_BUTTON,
    
    
    //tab3
    MT_LECTURE_HBOX,
    MT_RECITATION_HBOX,
    MT_LABS_HBOX,
    //labels
    MT_LECTURE_LABEL,
    MT_RECITATION_LABEL,
    MT_LABS_LABEL,
    //buttons
    MT_ADD_LECUTURE_BUTTON,
    MT_ADD_RECITATION_BUTTON,
    MT_ADD_LABS_BUTTON,
    MT_DELETE_LECUTURE_BUTTON,
    MT_DELETE_RECITATION_BUTTON,
    MT_DELETE_LABS_BUTTON,
    //tables
    MT_LECTURE_TABLE_VIEW,
    MT_RECITATION_TABLE_VIEW,
    MT_LABS_TABLE_VIEW,
    //lecture columns
    MT_LEC_SECTION_TABLE_COLUMN,
    MT_LEC_DAYS_TABLE_COLUMN,
    MT_LEC_TIME_TABLE_COLUMN,
    MT_LEC_ROOM_TABLE_COLUMN,
    //recitation columns
    MT_REC_SECTION_TABLE_COLUMN,
    MT_REC_DAYS_TIMES_TABLE_COLUMN,
    MT_REC_TA1_TABLE_COLUMN,
    MT_REC_TA2_TABLE_COLUMN,
    MT_REC_ROOM_TABLE_COLUMN,
    //labs columns
    MT_LAB_SECTION_TABLE_COLUMN,
    MT_LAB_DAYS_TIMES_TABLE_COLUMN,
    MT_LAB_TA1_TABLE_COLUMN,
    MT_LAB_TA2_TABLE_COLUMN,
    MT_LAB_ROOM_TABLE_COLUMN,
    
    //tab4
    SD_CALENDAR_VBOX,
    SD_TABLE_VBOX,
    SD_CALENDAR_BOUND_LABEL,
    SD_START_MON_LABEL,
    SD_END_FRI_LABEL,
    SD_ITEM_LABEL,
    SD_START_MON_DATE_PICKER,
    SD_END_FRI_DATE_PICKER,
    SD_SCHEDULE_ITEM_TABLE_VIEW,
    SD_DELETE_SCHEDULE_ITEM_BUTTON,
    //sd table columns
    SD_TYPE_TABLE_COLUMN,
    SD_DATE_TABLE_COLUMN,
    SD_TITLE_TABLE_COLUMN,
    SD_TOPIC_TABLE_COLUMN,
    //edit block
    SD_EDIT_VBOX,
    SD_ADD_EDIT_LABEL,
    SD_EDIT_TYPE_LABEL,
    SD_EDIT_DATE_LABEL,
    SD_EDIT_TITLE_LABEL,
    SD_EDIT_TOPIC_LABEL,
    SD_EDIT_LINK_LABEL,
    SD_TYPE_COMBO_BOX,
    SD_DATE_DATE_PICKER,
    SD_TITLE_TEXT_FIELD,
    SD_TOPIC_TEXT_FIELD,
    SD_LINK_TEXT_FIELD,
    SD_ADD_UPDATE_BUTTON,
    SD_CLEAR_BUTTON,
    
    //scroll panes
    SD_SCROLL_PANE,

    
    
    
    
    
    
    
}