package csg;

/**
 * This class provides the properties that are needed to be loaded for
 * setting up To Do List Maker workspace controls including language-dependent
 * text.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum CourseSitePropertyType {

    /* THESE ARE THE NODES IN OUR APP */
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    CSG_OK_PROMPT,
    OH_CANCEL_PROMPT,

    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    CSG_TAB_PANE,
    CSG_CENTER_PANE,
    CSG_LEFT_PANE,
    CSG_TAS_HEADER_PANE,
    CSG_TAS_HEADER_LABEL,
    CSG_GRAD_UNDERGRAD_TAS_PANE,
    CSG_ALL_RADIO_BUTTON,
    CSG_GRAD_RADIO_BUTTON,
    CSG_UNDERGRAD_RADIO_BUTTON,
    CSG_TAS_HEADER_TEXT_FIELD,
    CSG_TAS_TABLE_VIEW,
    CSG_NAME_TABLE_COLUMN,
    CSG_EMAIL_TABLE_COLUMN,
    CSG_SLOTS_TABLE_COLUMN,
    CSG_TYPE_TABLE_COLUMN,

    CSG_ADD_TA_PANE,
    CSG_NAME_TEXT_FIELD,
    CSG_EMAIL_TEXT_FIELD,
    CSG_ADD_TA_BUTTON,

    CSG_RIGHT_PANE,
    CSG_OFFICE_HOURS_HEADER_PANE,
    CSG_OFFICE_HOURS_HEADER_LABEL,
    CSG_OFFICE_HOURS_TABLE_VIEW,
    OH_START_TIME_TABLE_COLUMN,
    OH_END_TIME_TABLE_COLUMN,
    OH_MONDAY_TABLE_COLUMN,
    OH_TUESDAY_TABLE_COLUMN,
    OH_WEDNESDAY_TABLE_COLUMN,
    OH_THURSDAY_TABLE_COLUMN,
    OH_FRIDAY_TABLE_COLUMN,
    OH_DAYS_OF_WEEK,
    CSG_FOOLPROOF_SETTINGS,
    
    // FOR THE EDIT DIALOG
    CSG_TA_EDIT_DIALOG,
    CSG_TA_DIALOG_GRID_PANE,
    CSG_TA_DIALOG_HEADER_LABEL, 
    CSG_TA_DIALOG_NAME_LABEL,
    CSG_TA_DIALOG_NAME_TEXT_FIELD,
    CSG_TA_DIALOG_EMAIL_LABEL,
    CSG_TA_DIALOG_EMAIL_TEXT_FIELD,
    CSG_TA_DIALOG_TYPE_LABEL,
    CSG_TA_DIALOG_TYPE_BOX,
    CSG_TA_DIALOG_GRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_UNDERGRAD_RADIO_BUTTON,
    CSG_TA_DIALOG_OK_BOX,
    CSG_TA_DIALOG_OK_BUTTON, 
    CSG_TA_DIALOG_CANCEL_BUTTON, 
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    CSG_NO_TA_SELECTED_TITLE, CSG_NO_TA_SELECTED_CONTENT,
    
    // tabs
    CSG_SITE_TAB_BUTTON,
    CSG_SYLLUBUS_TAB_BUTTON,
    CSG_MEETING_TIME_TAB_BUTTON,
    CSG_SCHEDULE_TAB_BUTTON,
    CSG_OFFICE_HOUR_TAB_BUTTON,
    
    //tab1
    SITE_BANNER_HBOX,
    SITE_PAGE_HBOX,
    SITE_STYLE_HBOX,
    SITE_INSTRUCTOR_HBOX,
    SITE_SCROLL_PANE,
    
    //tab1 banner
    SITE_BANNER_LABEL,
    SITE_SBJ_COMBO_BOX,
    SITE_NUMBER_COMBO_BOX,
    SITE_SBJ_LABEL,
    SITE_NUMBER_LABEL,
    SITE_YEAR_LABEL,
    SITE_SEMESTER_LABEL,
    SITE_SEMESTER_COMBO_BOX,
    SITE_YEAR_COMBO_BOX,
    SITE_TITLE_LABEL,
    SITE_TITLE_TEXT_FIELD,
    SITE_EXPORT_DIR_LABEL,
    SITE_EXPORT_DIR,
    
    //tab1 page
    SITE_PAGE_LABEL,
    SITE_HOME_CHECK_BOX,
    SITE_SYLLUBUS_CHECK_BOX,
    SITE_SCHEDULE_CHECK_BOX,
    SITE_HWS_CHECK_BOX,
    
    //tab1 style
    SITE_STYLE_LABEL,
    SITE_NOTE_LABEL,
    
    //tab1 instructor
    SITE_INSTRUCTOR_LABEL,
    SITE_NAME_LABEL,
    SITE_EMAIL_LABEL,
    SITE_NAME_COMBO_BOX,
    SITE_EMAIL_COMBO_BOX,
    SITE_ROOM_LABEL,
    SITE_HOME_PAGE_LABEL,
    SITE_ROOM_COMBO_BOX,
    SITE_HOME_PAGE_COMBO_BOX,
    
    //tab2
    //labels
    SYLLUBUS_DES_LABEL,
    SYLLUBUS_TOPIC_LABEL,
    SYLLUBUS_PREQ_LABEL,
    SYLLUBUS_OUTCOME_LABEL,
    SYLLUBUS_TEXTBOOK_LABEL,
    SYLLUBUS_GRADED_COMP_LABEL,
    SYLLUBUS_GRADING_NOTE_LABEL,
    SYLLUBUS_ACAD_DIS_LABEL,
    SYLLUBUS_SPEC_ASSIST_LABEL,
    //textfields
    SYLLUBUS_DES_TEXTFIELD,
    SYLLUBUS_TOPIC_TEXTFIELD,
    SYLLUBUS_PREQ_TEXTFIELD,
    SYLLUBUS_OUTCOME_TEXTFIELD,
    SYLLUBUS_TEXTBOOK_TEXTFIELD,
    SYLLUBUS_GRADED_COMP_TEXTFIELD,
    SYLLUBUS_GRADING_NOTE_TEXTFIELD,
    SYLLUBUS_ACAD_DIS_TEXTFIELD,
    SYLLUBUS_SPEC_ASSIST_TEXTFIELD,
    
    //tab4
    
    
    
    
    
    
    
    
    
}